# Products
components:
  schemas:
    Product:
      type: object
      required:
        - id
        - title
        - price
        - code
        - stock
      properties:
        id:
          type: string
        title:
          type: string
        price:
          type: number
        thumbnail:
          type: string
        description:
          type: string
        code:
          type: string
        stock:
          type: number
      example:
        id: '1'
        nombre: Monitor
        price: 80
        thumbnail: https://via.placeholder.com/300/09f/fff.png
        description: Monitor Samsung LCD
        code: TEC10
        stock: 10