PUT http://localhost:8080/api/products/62a752f1d259cb2419e2e14b
content-type: application/json

{
    "title": "Computadora actualizado",
    "price": 1500,
    "thumbnail": "https://res.cloudinary.com/dnwlad3kp/image/upload/v1637962406/compragamer_Imganen_general_21800_Notebook_ASUS_x509_15_udyq3y.png",
    "description": "Notebook HP 8GB RAM",
    "code": "405fth",
    "stock": 8
}